### ISSUE TITLE
【BUG】登录解析出错

### ISSUE THREAD

**Issue by oniLand** [tonquer/ehentai-windows#4]
错误打印
```
2021-09-15 22:15:39,058 - user_handler.py[line:198] - ERROR: 'NoneType' object has no attribute 'replace'
Traceback (most recent call last):
  File "src\server\user_handler.py", line 189, in __call__
  File "src\server\server.py", line 132, in Send
  File "src\server\server.py", line 129, in __DealHeaders
  File "src\util\tool.py", line 94, in GetUrlHost
AttributeError: 'NoneType' object has no attribute 'replace'

```
不登录可以正常解析表站
我登录后可以切换里站 但是表里都提示无法解析
![image](https://user-images.githubusercontent.com/21368333/133450726-ebba5ac7-74ac-499c-8429-2d19f668e61f.png)

**Comment by oniLand** [comment]
v1.0.3

**Comment by tonquer** [comment]
修复了，可以试试
https://github.com/tonquer/ehentai-windows/actions/runs/1238216806

**Comment by oniLand** [comment]
谢谢，可以解析了。
